{
 "title": "HeliumValidator",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "In Consensus Group",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "validator_inconsensus{resource_type=\"howling-tin-pangolin\"}",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Penalty",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_hbbft_penalty{instance=\"10.0.0.50:8000\"}",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_usage{instance=\"10.0.0.50:8000\"}",
     "legendFormat": "{{resource_type}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"10.0.0.50:9100\",device=\"docker0\"}[1m])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"10.0.0.50:9100\",device=\"docker0\"}[1m])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Blockchain Height",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_height{instance=\"10.0.0.50:8000\",job=\"prometheus\"}"
    }
   ]
  }
 ]
}